export enum MoveTypes {
  CANDIDATE = "CANDIDATE",
  NUMBER = "NUMBER"
}

export enum GameLevel {
  EASY = "EASY",
  MEDIUM = "MEDIUM",
  HARD = "HARD",
  EXPERT = "EXPERT"
}

export const ALLOWED_MISTAKES = 3

export interface Move {
  coordinate: Coordinate
  value: number
  type: MoveTypes
}

export interface Cell {
  autogenerated: boolean;
  value?: number;
  solution: number;
  coordinate: Coordinate;
}

export interface Coordinate {
  x: number;
  y: number;
}

export interface NumberDifficulty {
  [key: number]: {count: number}
}

